# config.toml

[configuration]
mem_size        = 8192
clock           = 1000.0
run+mode        = "stepped"
monitor_size_x  = 40
monitor_size_y  = 20
logging         = True

[initialization]
status_reg      = 0b00100000
stack_pointer   = 0x00
cycle_counter   = 0x00000000